" Vundle Configuration
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


syntax enable           " enable syntax processing

set tabstop=4		" number of visual spaces per TAB
set softtabstop=4	" number of spaces in TAB when editing
set expandtab		" spaces not tabs
set number          " enable line numbering
set wrap            " wrap lines that are too wide for the screen
set showmatch		" show matching parens, brackets, etc.

set incsearch		" start searching as I type
set hlsearch		" highlight search matches

" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>

" handle navigation across wrapped lines
nnoremap j gj
nnoremap k gk

" sane navigation to begin/end of lines
nnoremap B ^
nnoremap E $
nnoremap $ <nop>
nnoremap ^ <nop>

" Replace esc with jj
inoremap jj <esc>

" strips trailing whitespace at the end of files.
function! <SID>StripTrailingWhitespaces()
    " save last search & cursor position
    let _s=@/
    let l = line(".")   
    let c = col(".")
    %s/\s\+$//e
    let @/=_s
    call cursor(l, c)
endfunction
